apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-webhook
  labels:
    app: validate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validate
  template:
    metadata:
      labels:
        app: validate
    spec:
      containers:
      - name: webhook
        image: ugurozturk99/custodes:${CI_PIPELINE_ID}
        ports:
        - containerPort: 443
        env:
        - name: cpu
          value: "2"
        volumeMounts:
        - mountPath: "/app/properties.yaml"
          name: config
          subPath: "properties.yaml"
        - name: certs-volume
          readOnly: true
          mountPath: "/certs"
        imagePullPolicy: Always
      volumes:
      - name: config
        configMap:
          name: webhook-cm
          items:
          - key: "properties.yaml"
            path: "properties.yaml"
      - name: certs-volume
        secret:
          secretName: admission-tls
